services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jarvis
    ports:
      - "5432:5432"  
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql