### login
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "danielsampaio.dev@gmail.com"
}

### create account
POST http://localhost:3333/accounts
Content-Type: application/json

{
  "email": "danielsampaio.dev@gmail.com",
  "name": "Daniel Sampaio"
}

### ask-ai
POST http://localhost:3333/ask-ai
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTVhYjE3Mi02NDgyLTQyNDYtOTJmYS02NjE2YjdhYjZhYTMiLCJpYXQiOjE3NTc0NTI1MjMsImV4cCI6MTc1NzUzODkyM30.uAc9pUShsk4xRI4EK2R9m8nD4gj8E7CqDBY75yclI-k

{
  "question": "oi"
}
