### login
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Leon72@hotmail.com"
}

### create account
POST http://localhost:3333/accounts
Content-Type: application/json

{
  "email": "danielsampaio.dev@gmail.com",
  "name": "Daniel Sampaio"
}

### ask-ai
POST http://localhost:3333/ask-ai
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MmY2ZmUxYy0xODJhLTRmOWQtYjkxNy1mODE4Y2MyNDg0MzkiLCJpYXQiOjE3NTg5MTczMDMsImV4cCI6MTc1OTAwMzcwM30.0QksV9AfwgLkkyhhQKp6PFYx4huFQloMXVHcXPoAqUg

{
  "question": "mostre minhas transacoes"
}

### create checkout
POST http://localhost:3333/checkout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNTVhYjE3Mi02NDgyLTQyNDYtOTJmYS02NjE2YjdhYjZhYTMiLCJpYXQiOjE3NTc1NjAxMzcsImV4cCI6MTc1NzY0NjUzN30.9gEW6HT4SM5Fcj6NP0CsEtJDLU0lPTGYwCzrkzc31Qw


{
  "priceId": "price_1S5AyLDYLRFg5faysqHgDFWp"
}
